-- ==============================================================================
-- PROJECT: Title Operations SLA Audit
-- AUTHOR: Alpha Oumar II Bah
-- PURPOSE: Diagnostic queries to identify SLA breaches and interest penalty risk
-- ==============================================================================
